#!/bin/bash

echo "Esta linha não tem erro" > ficheiro
echo "Aqui está a palavra erro no meio" >> ficheiro
echo "Linha sem erro" >> ficheiro
echo "Outro erro aqui para testar" >> ficheiro
echo "Mais uma linha sem erro" >> ficheiro
echo "Ultima linha com erro no final" >> ficheiro

# Numero de linhas
num_linhas=$(wc -l < ficheiro)
echo "Número de linhas: $num_linhas"

# Contar o número de palavras no arquivo
num_palavras=$(wc -w < ficheiro)
echo "Número de palavras: $num_palavras"

# Passo 4: Filtrar e exibir as linhas que contêm a palavra "erro"
echo "Linhas que contêm 'erro':"
grep "erro" ficheiro
